import numpy as np
import gymnasium as gym
from gymnasium.spaces import Box, Discrete
from data_models.base_tower import BaseTower
from data_models.car_fcd_data import CarFcdData
from data_models.handover_algorithm import HandoverAlgorithm
from data_models.ng_ran_report import NGRANReport
from data_models.user_equipment import UserEquipment
from utils.fcd_parser import FcdParser
from utils.map_downloader import MapDownloader
from utils.path_gen import PathGeneration
from utils.tower_downloader import TowerDownloader
from utils.wave_utils import WaveUtils


class HandoverEnv(gym.Env):

    def __init__(self, top_left: float, bottom_right: float, mcc: int):
        super().__init__()
        # Prepare Env
        PathGeneration.quick_run(skip_netconvert=False)
        MapDownloader.download_osm_by_bbox(
            top_left=top_left,
            bottom_right=bottom_right,
        )
        self.base_towers: list[BaseTower] = TowerDownloader.download_towers_in_bbox(
            top_left=top_left,
            bottom_right=bottom_right,
            mcc=mcc,
        )
        self.fcd_data: list[dict[int, CarFcdData]] = None  # Created on reset()
        self.agent: UserEquipment = None  # Created on reset()
        # Top-4 Filtering
        self.current_top_4: list[BaseTower] = []
        # action space: choosing 1 of 4 BS
        self.action_space = Discrete(4)
        # observation Space
        self.observation_space = Box(low=0.0, high=1.0, shape=(12,), dtype=np.float32)

        self.steps = 0

    def _top_4_towers(self, report: NGRANReport):
        rsrp_weight = 0.5
        rsrq_weight = 0.5

        scores: dict[int, float] = {}

        for bs in self.base_towers:
            bs_id = bs.id

            norm_rsrp = WaveUtils.normalize_rsrp_index(
                report.rsrp_values.get(bs_id, 0), bs.radio
            )
            norm_rsrq = WaveUtils.normalize_rsrq_index(
                report.rsrq_values.get(bs_id, 0), bs.radio
            )

            scores[bs_id] = (norm_rsrp * rsrp_weight) + (norm_rsrq * rsrq_weight)

        sorted_scores = sorted(scores.items(), key=lambda item: item[1], reverse=True)

        top_4_ids = [item[0] for item in sorted_scores[:4]]

        tower_lookup = {bs.id: bs for bs in self.base_towers}
        top_4_towers = [tower_lookup[t_id] for t_id in top_4_ids]

        return top_4_towers

    def _get_obs(self):
        # NOTE: obs is normalized
        if len(self.agent.generated_reports) < 1:
            return np.zeros(self.observation_space.shape, dtype=np.float32)
        # last report generated by the agent
        report: NGRANReport = self.agent.generated_reports[-1]

        # extract RSRP/RSRQ values from the 4 towers, normalize to 0-1
        rsrp_list = [
            WaveUtils.normalize_rsrp_index(
                rsrp_index=report.rsrp_values.get(bs.id, 0),
                radio_type=bs.radio,
            )
            for bs in self.current_top_4
        ]
        rsrq_list = [
            WaveUtils.normalize_rsrq_index(
                rsrq_index=report.rsrq_values.get(bs.id, 0),
                radio_type=bs.radio,
            )
            for bs in self.current_top_4
        ]
        # connected tower index (guaranteed to have a serving bs since generated reports >= 1)
        serving_one_hot = [0, 0, 0, 0]
        if self.agent.serving_bs in self.current_top_4:
            serving_position = self.current_top_4.index(self.agent.serving_bs)
            serving_one_hot[serving_position] = 1
        # observation, serving_one_hot will be [0,0,0,0] if ue is not connected to any tower
        obs = np.concatenate([rsrp_list, rsrq_list, serving_one_hot], dtype=np.float32)
        return obs

    def step(self, action):
        """Execute the action Handover/No Handover then move all the cars once"""
        # Reset() guarantees current_top_4 is populated
        target_bs = self.current_top_4[action]
        # NOTE: increase to reduce pingpong, reduce to improve RSRP/RSRQ
        handover_penalty = 0.1
        current_fcd_dict: dict[int, CarFcdData] = self.fcd_data[self.steps]
        if self.agent.id not in current_fcd_dict:
            # The car reached its destination, Episode terminated.
            obs = self._get_obs()
            return obs, 0.0, True, False, {"info": "Agent vehicle reached destination."}

        timestep = current_fcd_dict[self.agent.id].timestep
        tower_before_action = self.agent.serving_bs
        handover_executed = False
        # --- Execute Action ---
        if self.agent.serving_bs != target_bs:
            if self.agent.serving_bs is None:
                self.agent.connect_to_tower(bs=target_bs, timestep=timestep)
            else:
                # Trigger Handover
                self.agent.handover(target_bs, timestep=timestep)
                handover_executed = True

        # Move cars once, to get new
        if self.steps < len(self.fcd_data):
            fcds = self.fcd_data[self.steps].values()
            for fcd in fcds:
                car = self.user_equipments.get(fcd.id)
                if car:
                    # All Cars will initiate the handover after moving using A3_RSRP except the agent (HandoverAlgorithm.NONE)
                    car.move_to(fcd.latlng, timestep=fcd.timestep)

        # Agent will have a new serving_bs ONLY if the action was to handover: [self.agent.handover(target_bs, timestep=timestep)]
        """
        The handover() func inside the UE explicitly says:         
        if self.serving_bs == target_bs:
            return
        """
        tower_after_action = self.agent.serving_bs

        report_after = self.agent.generated_reports[-1]

        # --- Update Top 4 ---
        self.current_top_4 = self._top_4_towers(report_after)

        # --- Calculate Reward ---
        if len(self.agent.generated_reports) >= 2 and tower_before_action is not None:
            report_before = self.agent.generated_reports[-2]

            rsrp_before = WaveUtils.normalize_rsrp_index(
                report_before.rsrp_values.get(tower_before_action.id, 0),
                tower_before_action.radio,
            )
            rsrp_after = WaveUtils.normalize_rsrp_index(
                report_after.rsrp_values.get(tower_after_action.id, 0),
                tower_after_action.radio,
            )
            rsrq_before = WaveUtils.normalize_rsrq_index(
                report_before.rsrq_values.get(tower_before_action.id, 0),
                tower_before_action.radio,
            )
            rsrq_after = WaveUtils.normalize_rsrq_index(
                report_after.rsrq_values.get(tower_after_action.id, 0),
                tower_after_action.radio,
            )

            delta_rsrp = rsrp_after - rsrp_before
            delta_rsrq = rsrq_after - rsrq_before

            if handover_executed:
                reward = delta_rsrp + delta_rsrq - handover_penalty
            else:
                # Did we ignore the better tower?
                # Handover wasnt executed, this means tower_before_action = tower_after_action, Check the state if the user missed any opportunities
                # check what was in the top-4 towers, get the best one and use it to punish staying on a worse tower, only then we can update self.current_top_4
                best_rsrp = max(
                    WaveUtils.normalize_rsrp_index(
                        report_after.rsrp_values.get(bs.id, 0), bs.radio
                    )
                    for bs in self.current_top_4
                )
                best_rsrq = max(
                    WaveUtils.normalize_rsrq_index(
                        report_after.rsrq_values.get(bs.id, 0), bs.radio
                    )
                    for bs in self.current_top_4
                )
                reward = (rsrp_after - best_rsrp) + (rsrq_after - best_rsrq)

        else:
            reward = 0.0

        self.steps += 1
        truncated = self.steps >= len(self.fcd_data)  # End of the SUMO trace
        terminated = False
        info = {}  # TODO: add info if needed in the future

        obs = self._get_obs()

        return obs, float(reward), terminated, truncated, info

    def reset(self, seed=None, options=None):
        super().reset(seed=seed, options=options)
        self.steps = 0

        # Generate new randomized traffic scenario (quick_run has a random seed built in)
        PathGeneration.quick_run(skip_netconvert=True)
        self.fcd_data = FcdParser.parse_fcd_trace()
        num_ue = FcdParser.count_vehicles()

        # Reinitialize UEs
        # User 0 shouldnt (our agent) have a handover algorithm, the env wil manage that, other UE's are free (A3 RSRP 3GPP)
        self.user_equipments = {
            i: UserEquipment(
                id=i,
                all_bs=self.base_towers,
                print_logs_on_movement=False,
                handover_algorithm=(
                    HandoverAlgorithm.NONE if i == 0 else HandoverAlgorithm.A3_RSRP_3GPP
                ),
            )
            for i in range(num_ue)
        }
        self.agent = self.user_equipments[0]

        # Move the agent to its starting position to generate the first report TODO: make sure the report is generated
        # one of the checks is enough, just for safety
        if len(self.fcd_data) > 0 and self.agent.id in self.fcd_data[0]:
            start_data = self.fcd_data[0][self.agent.id]
            report = self.agent.move_to(start_data.latlng, timestep=start_data.timestep)
            self.current_top_4 = self._top_4_towers(report)
        else:
            # Fallback just in case Car 0 doesn't spawn until timestep 2
            self.current_top_4 = self.base_towers[:4]

        obs = self._get_obs()
        info = {}
        return obs, info
