import numpy as np
import gymnasium as gym
from gymnasium.spaces import Box, Discrete
from data_models.base_tower import BaseTower
from data_models.car_fcd_data import CarFcdData
from data_models.handover_algorithm import HandoverAlgorithm
from data_models.ng_ran_report import NGRANReport
from data_models.user_equipment import UserEquipment
from helpers.filters import Filters
from utils.fcd_parser import FcdParser
from utils.map_downloader import MapDownloader
from utils.path_gen import PathGeneration
from utils.tower_downloader import TowerDownloader
from utils.wave_utils import WaveUtils


class HandoverEnv(gym.Env):

    def __init__(
        self,
        top_left: float,
        bottom_right: float,
        mcc: int,
        step_len: int,
        simulation_time: float,
    ):
        super().__init__()
        # Prepare Env
        PathGeneration.quick_run(
            skip_netconvert=False,
            step_length=step_len,
            simulation_time=simulation_time,
        )
        MapDownloader.download_osm_by_bbox(
            top_left=top_left,
            bottom_right=bottom_right,
        )
        self.base_towers: list[BaseTower] = TowerDownloader.download_towers_in_bbox(
            top_left=top_left,
            bottom_right=bottom_right,
            mcc=mcc,
        )
        self.fcd_data: list[dict[int, CarFcdData]] = None  # Created on reset()
        self.agent: UserEquipment = None  # Created on reset()
        # Top-4 Filtering
        self.current_top_4: list[BaseTower] = []
        # action space: choosing 1 of 4 BS
        self.action_space = Discrete(4)
        # observation Space
        self.observation_space = Box(low=0.0, high=1.0, shape=(12,), dtype=np.float32)
        self.step_len = step_len
        self.simulation_time = simulation_time

        self.steps = 0

    def _top_4_towers(self, report: NGRANReport):
        return Filters.top_k_towers(
            all_bs=self.base_towers,
            report=report,
            k=4,
        )

    def _get_obs(self):
        # NOTE: obs is normalized
        if len(self.agent.generated_reports) < 1:
            return np.zeros(self.observation_space.shape, dtype=np.float32)
        # last report generated by the agent
        report: NGRANReport = self.agent.generated_reports[-1]

        # extract RSRP/RSRQ values from the 4 towers, normalize to 0-1
        rsrp_list = [
            WaveUtils.normalize_rsrp_index(
                rsrp_index=report.rsrp_values.get(bs.id, 0),
                radio_type=bs.radio,
            )
            for bs in self.current_top_4
        ]
        rsrq_list = [
            WaveUtils.normalize_rsrq_index(
                rsrq_index=report.rsrq_values.get(bs.id, 0),
                radio_type=bs.radio,
            )
            for bs in self.current_top_4
        ]
        # connected tower index (guaranteed to have a serving bs since generated reports >= 1)
        serving_one_hot = [0, 0, 0, 0]
        if self.agent.serving_bs in self.current_top_4:
            serving_position = self.current_top_4.index(self.agent.serving_bs)
            serving_one_hot[serving_position] = 1
        # observation, serving_one_hot will be [0,0,0,0] if ue is not connected to any tower
        obs = np.concatenate([rsrp_list, rsrq_list, serving_one_hot], dtype=np.float32)
        return obs

    def step(self, action):
        """Execute the action Handover/No Handover then move all the cars once"""
        # Reset() guarantees current_top_4 is populated
        target_bs = self.current_top_4[action]
        # NOTE: increase to reduce pingpong, reduce to improve RSRP/RSRQ
        handover_penalty = 0.1
        current_fcd_dict: dict[int, CarFcdData] = self.fcd_data[self.steps]
        if self.agent.id not in current_fcd_dict:
            # The car reached its destination, Episode terminated.
            obs = self._get_obs()
            return obs, 0.0, True, False, {"info": "Agent vehicle reached destination."}

        timestep = current_fcd_dict[self.agent.id].timestep
        tower_before_action = self.agent.serving_bs
        handover_executed = False
        # --- Execute Action ---
        if self.agent.serving_bs != target_bs:
            if self.agent.serving_bs is None:
                self.agent.connect_to_tower(bs=target_bs, timestep=timestep)
            else:
                # Trigger Handover For the agent only.
                self.agent.handover(target_bs, timestep=timestep)
                handover_executed = True

        # Move cars once, to get new
        total_timesteps = len(self.fcd_data)
        if self.steps < total_timesteps:
            fcds = self.fcd_data[self.steps].values()
            for fcd in fcds:
                car = self.user_equipments.get(fcd.car_id)
                if car:
                    # All Cars will initiate the handover after moving using A3_RSRP except the agent (HandoverAlgorithm.NONE)
                    car.move_to(
                        fcd.latlng,
                        timestep=fcd.timestep,
                        speed=fcd.speed,
                        angle=fcd.angle,
                    )

        # Agent will have a new serving_bs ONLY if the action was to handover: [self.agent.handover(target_bs, timestep=timestep)]
        """
        The handover() func inside the UE explicitly says:         
        if self.serving_bs == target_bs:
            return
        """
        tower_after_action = self.agent.serving_bs

        report_after = self.agent.generated_reports[-1]

        # --- Update Top 4 ---
        self.current_top_4 = self._top_4_towers(report_after)

        # --- Calculate Reward ---
        if len(self.agent.generated_reports) >= 2 and tower_before_action is not None:

            rsrp_stayed = WaveUtils.normalize_rsrp_index(
                report_after.rsrp_values.get(tower_before_action.id, 0),
                tower_before_action.radio,
            )
            rsrp_current = WaveUtils.normalize_rsrp_index(
                report_after.rsrp_values.get(tower_after_action.id, 0),
                tower_after_action.radio,
            )
            rsrq_stayed = WaveUtils.normalize_rsrq_index(
                report_after.rsrq_values.get(tower_before_action.id, 0),
                tower_before_action.radio,
            )
            rsrq_current = WaveUtils.normalize_rsrq_index(
                report_after.rsrq_values.get(tower_after_action.id, 0),
                tower_after_action.radio,
            )

            delta_rsrp = rsrp_current - rsrp_stayed
            delta_rsrq = rsrq_current - rsrq_stayed

            if handover_executed:
                reward = delta_rsrp + delta_rsrq - handover_penalty
            else:
                # Did we ignore the better tower?
                # Handover wasnt executed, this means tower_before_action = tower_after_action, Check the state if the user missed any opportunities
                # check what was in the top-4 towers, get the best one and use it to punish staying on a worse tower
                best_rsrp = max(
                    WaveUtils.normalize_rsrp_index(
                        report_after.rsrp_values.get(bs.id, 0), bs.radio
                    )
                    for bs in self.current_top_4
                )
                best_rsrq = max(
                    WaveUtils.normalize_rsrq_index(
                        report_after.rsrq_values.get(bs.id, 0), bs.radio
                    )
                    for bs in self.current_top_4
                )
                reward = (rsrp_current - best_rsrp) + (rsrq_current - best_rsrq)

        else:
            reward = 0.0

        self.steps += 1
        truncated = self.steps >= total_timesteps  # End of the SUMO trace
        terminated = False
        info = {
            "timestep": self.steps,
            "total_timesteps": total_timesteps,
        }
        obs = self._get_obs()

        return obs, float(reward), terminated, truncated, info

    def reset(self, seed=None, options=None):
        super().reset(seed=seed, options=options)
        self.steps = 0
        WaveUtils.reset_fading_state()

        # Generate new randomized traffic scenario (quick_run has a random seed built in)
        PathGeneration.quick_run(
            skip_netconvert=True,
            step_length=self.step_len,
            simulation_time=self.simulation_time,
        )
        self.fcd_data = FcdParser.parse_fcd_trace()
        num_ue = FcdParser.count_vehicles()

        # Reinitialize UEs
        # User 0 shouldnt (our agent) have a handover algorithm, the env wil manage that, other UE's are free (A3 RSRP 3GPP)
        self.user_equipments = {
            i: UserEquipment(
                id=i,
                all_bs=self.base_towers,
                print_logs_on_movement=False,
                handover_algorithm=(
                    HandoverAlgorithm.NONE if i == 0 else HandoverAlgorithm.A3_RSRP_3GPP
                ),
            )
            for i in range(num_ue)
        }
        self.agent = self.user_equipments[0]

        # Move the agent to its starting position to generate the first report
        # one of the checks is enough, just for safety
        if len(self.fcd_data) > 0 and self.agent.id in self.fcd_data[0]:
            start_data = self.fcd_data[0][self.agent.id]
            report = self.agent.move_to(
                start_data.latlng,
                timestep=start_data.timestep,
                speed=start_data.speed,
                angle=start_data.angle,
            )
            self.current_top_4 = self._top_4_towers(report)
        else:
            # Fallback just in case Car 0 doesn't spawn until timestep 2
            self.current_top_4 = self.base_towers[:4]

        obs = self._get_obs()
        info = {}
        return obs, info
